// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqecrnfpaegqidwyhxdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxZWNybmZwYWVncWlkd3loeGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODUzODksImV4cCI6MjA3MDE2MTM4OX0.QbKifL-EJhuzXt2BDBIYko7JE_eIzC0NCqTHU_hqbic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});